name: 'Is Maintainer Action'
description: 'Check if the actor is a maintainer of the repository'
inputs:
  token:
    description: 'The GitHub token used to make API requests'
    required: true
  actor:
    description: 'The actor to check for maintainer status'
    required: true
runs:
  using: 'composite'
  steps:
    - id: is-maintainer
      run: |
        is_maintainer=$(curl -s -H "Authorization: token ${{ inputs.token }}" https://api.github.com/repos/${{ github.repository }}/collaborators/${{ inputs.actor }}/permission | jq -r '.permission')
        if [ "$is_maintainer" = "admin" ] || [ "$is_maintainer" = "write" ]; then
          echo "The actor is a maintainer of the repository"
          echo "isMaintainer=true" >> $GITHUB_ENV
        else
          echo "The actor is NOT a maintainer of the repository"
          echo "isMaintainer=false" >> $GITHUB_ENV
        fi
      shell: bash
