name: Run Tests If Admin

on:
  push:
    branches: [ "main", "production" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  check-admin:
    runs-on: ubuntu-latest
    outputs:
      isAdmin: ${{ steps.checkUser.outputs.require-result }}
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          require: 'admin'

  request-approval:
    needs: check-admin
    if: needs.check-admin.outputs.isAdmin == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment for manual approval
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "This PR requires manual approval by a maintainer. @maintainer, please review the changes and trigger the 'Manual Approval' workflow if everything looks good."
            });

  build:
    needs: check-admin
    if: needs.check-admin.outputs.isAdmin == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Run tests
        run: yarn test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - run: yarn build
