name: Node.js CI

on:
  push:
    branches: [ "main", "production" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  check-maintainer:
    runs-on: ubuntu-latest
    outputs:
      isMaintainer: ${{ steps.check-maintainer.outputs.isMaintainer }}
    steps:
      - name: Check if actor is a maintainer
        id: check-maintainer
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const collaborators = await github.rest.repos.listCollaborators(context.repo);
            const maintainer = collaborators.data.find(
              (collaborator) => collaborator.login === github.actor && collaborator.permissions.admin
            );
            return { isMaintainer: !!maintainer };

  request-approval:
    if: needs.check-maintainer.outputs.isMaintainer == 'false'
    needs: check-maintainer
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment for manual approval
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "This PR requires manual approval by a maintainer. @maintainer, please review the changes and trigger the 'Manual Approval' workflow if everything looks good."
            });

  build:
    needs: check-maintainer
    if: needs.check-maintainer.outputs.isMaintainer == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Run tests
        run: yarn test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - run: yarn build
  publish:
    needs: build
    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
