name: Release

on:
  push:
    branches:
      - production

concurrency: ${{ github.workflow }}-${{ github.ref }}

# allow the action to create a pull request and to push to the branch
permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
